project:
  type: book

book:
  title: "Aprendizaje Máquina para Riesgos"
  author: "Felipe González"
  chapters:
    - index.qmd
    - 01-introduccion.qmd


bibliography: referencias/book.bib

format:
  html:
    theme: journal
    lang: es
    font-size: 1.1em
    code-fold: false



